# Generated by Django 3.0.1 on 2020-10-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technoplayer',
            name='loan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
