# Generated by Django 3.0.1 on 2020-10-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payback', '0003_auto_20201020_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technoplayer',
            name='user',
        ),
    ]
